# Generated by Django 4.0.6 on 2022-07-27 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False, verbose_name='좋아요')),
                ('content', models.TextField(verbose_name='내용')),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
                ('photo', models.ImageField(blank=True, upload_to='posts/%Y%m%d', verbose_name='사진')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200, verbose_name='댓글')),
                ('like', models.BooleanField(default=False, verbose_name='좋아요')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='posts.post')),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글',
                'ordering': ['-created_at'],
            },
        ),
    ]
