# Generated by Django 4.0.6 on 2022-07-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
        migrations.AddField(
            model_name='post',
            name='bookmark',
            field=models.BooleanField(default=False, verbose_name='즐겨찾기'),
        ),
    ]
