# Generated by Django 4.0.6 on 2022-07-20 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('kind', models.CharField(max_length=50, verbose_name='kind')),
                ('content', models.TextField(verbose_name='content')),
            ],
        ),
        migrations.CreateModel(
            name='OrderBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(choices=[('recent', '최신순'), ('create', '등록순'), ('name', '이름순'), ('select', '찜하기순')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('image', models.ImageField(blank=True, upload_to='idea/%Y%m%d', verbose_name='image')),
                ('content', models.TextField(verbose_name='content')),
                ('interset', models.IntegerField(verbose_name='interest')),
                ('select', models.BooleanField(default=False, verbose_name='select')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('devtool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devtool_list', to='ideas.devtool')),
            ],
        ),
    ]
