# Generated by Django 4.0.6 on 2022-07-20 18:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_rename_interset_idea_interest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderBy',
        ),
        migrations.AlterField(
            model_name='idea',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
