# Generated by Django 4.0.6 on 2022-07-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('date', models.IntegerField(verbose_name='개봉 년도')),
                ('genre', models.CharField(max_length=50, verbose_name='장르')),
                ('score', models.FloatField(verbose_name='별점')),
                ('runningtime', models.CharField(max_length=50, verbose_name='상영 시간')),
                ('reviewcontent', models.TextField(verbose_name='리뷰')),
                ('director', models.CharField(max_length=50, verbose_name='감독')),
                ('actors', models.CharField(max_length=50, verbose_name='배우')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
