# Generated by Django 4.0.6 on 2022-07-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='genre',
            field=models.CharField(choices=[('SF', 'SF'), ('판타지', '판타지'), ('액션', '액션'), ('로맨스', '로맨스'), ('코미디', '코미디'), ('애니메이션', '애니메이션'), ('공포', '공포'), ('멜로', '멜로'), ('스릴러', '스릴러')], max_length=50, verbose_name='장르'),
        ),
    ]
